/oak:
  ros__parameters:
    camera:
      i_enable_imu: true
      i_enable_ir: true
      i_pipeline_type: RGBD
      i_nn_type: none
      i_usb_speed: SUPER_PLUS
    rgb:
      i_resolution: "1080P"
      i_fps: 15.0
      i_publish_topic: true
    stereo:
      i_subpixel: false
      i_lr_check: true
      i_resolution: "400P"
      i_fps: 10.0
      i_publish_topic: true
      i_output_disparity: false
